### PR TITLE
refactor code, centralizing data retrieval with CacheFactory

### PR DESCRIPTION
**Pull request by shivaalipour**

### CODE REVIEW

**Comment by david-waltermire** [comment]
This PR is working to address #111.

**Comment by david-waltermire** [comment]
These changes did simplify the code quite a bit. Great job!

I have a few questions that may lead to follow-on work.
- How do we prove that this code is working properly? How do we incorporate some form of unit testing?
- Does this change address #112 in any way?

**Comment by gsavanderhyden** [comment]
> * How do we prove that this code is working properly? How do we incorporate some form of unit testing?
> * Does this change address ["X Clear Filters" function on the Marketplace (https://marketplace.fedramp.gov/) issue #112](https://github.com/GSA/marketplace-fedramp-gov/issues/112) in any way?

Thanks @david-waltermire - I will work with @shivaalipour to form a detailed test plan and execute test cases so we have documented proof that all aspects of this application are working as expected.

I took a peek at Issue 112 and found a case where clearing previously-filtered fields can be partially missed when a clear is performed.  Subsequent filters that believe they are turning the filter on are actually turning them off in the background.  I will add the fix to Sprint-2 branch, and we can add extensive filtering and searching test cases to the test plan.

**Comment by gsavanderhyden** [comment]
[Test Plan 2024-11-18 - FedRAMP Marketplace.xlsx](https://github.com/user-attachments/files/17805580/Test.Plan.2024-11-18.-.FedRAMP.Marketplace.xlsx)
Test plan attached.  All test cases successfully validated with @shivaalipour

**Review by david-waltermire — APPROVED** [review]
Thanks for providing the validated test plan.

**Pull request merged**
